### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by limengran98** [Xiaoshunxin/GNN-Survey#1]
作者您好，
我是一名科研工作者。
拜读了您的文章，同时想自己尝试一下复现，可是我自己在PyG上下载数据集速度太慢了。
不知可否方便将本文所有数据集公开呢，本人邮箱:1127147088@qq.com。感激不尽。

**Comment by Xiaoshunxin** [comment]
已发送到邮箱1127147088@qq.com
